name: Python application

on:
  push:
    branches: [ hw-3-grep ]
  pull_request:
    branches: [ hw-3-grep ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Test with pytest
      run: |
        bash run_tests.sh
    - name: Codestyle check
      run: |
        pycodestyle --max-line-length=120 --ignore=E402,E221 --exclude=plys/* .
